### ISSUE TITLE
Broken on Sept 2nd

### ISSUE THREAD

**Issue by acicali** [operator27c/firewalld-block-ipset#4]
Just a heads up, this script became non-functional by adding "set -o errexit". On first run, the command `firewall-cmd --permanent --delete-ipset=blocklist_v4` throws the error: **Error: INVALID_IPSET: blocklist_v4** and the script then exits. It will never get beyond this point.

**Comment by operator27c** [comment]
Good catch, thank you for reporting it. I didn't think about the first-run case...errors out when it tries to delete a nonexistent ipset. I'll adjust and push an update shortly.
